[[main]]
  name = "About"
  pageRef = "/about/"
  weight = 10

[[main]]
  name = "News"
  pageRef = "/news/"
  weight = 20

[[main]]
  name = "Projects"
  pageRef = "/projects/"
  weight = 30

[[main]]
  name = "Status"
  pageRef = "/status/"
  weight = 40

[[main]]
  name = "Sample project"
  pageRef = "/projects/sample-project/"
  parent = "Projects"
  weight = 1

[[main]]
  name = "Another project"
  pageRef = "/projects/another-project/"
  parent = "Projects"
  weight = 2

[[main]]
  name = "Yet Another project"
  pageRef = "/projects/yet-another-project/"
  parent = "Projects"
  weight = 3

[[main]]
  name = "Docs"
  pageRef = "/docs/"
  weight = 50

[[main]]
  name = "Sample doc"
  pageRef = "/docs/sample-doc/"
  parent = "Docs"
  weight = 1

[[main]]
  name = "Applying for access"
  pageRef = "/docs/short-term-project-storage/apply-for-access-to-a-gws/"
  parent = "Docs"
  weight = 2

[[social]]
  name = "X / Twitter"
  pre = "fab fa-x-twitter"
  url = "https://twitter.com/cedanews"
  weight = 20

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/cedadev"
  weight = 30

#[[social]]
#  name = "LinkedIn"
#  pre = "fab linkedin"
#  url = "https://linkedin.com/"
#  weight = 40

#[[social]]
#  name = "Medium"
#  pre = "fab medium"
#  url = "https://medium.com/"
#  weight = 50

# toml-docs-start sample-navigation
[[sample]]
  name = "Blog"
  pageRef = "/news/"
  weight = 10

[[sample]]
  name = "Projects"
  pageRef = "/projects/"
  weight = 20

[[sample]]
  name = "Sample project"
  pageRef = "/projects/sample-project/"
  parent = "Projects"
  weight = 1

[[sample]]
  name = "Another project"
  pageRef = "/projects/another-project/"
  parent = "Projects"
  weight = 2
# toml-docs-end sample-navigation