[[main]]
  name = "News"
  pageRef = "/news/"
  weight = 10

[[main]]
  name = "Events"
  pageRef = "/events/"
  weight = 20

[[main]]
  name = "Status"
  pageRef = "/status/"
  weight = 30
  
[[main]]
  name = "Projects"
  pageRef = "/projects/"
  weight = 40

[[main]]
  name = "TechBlog"
  url = "https://techblog.ceda.ac.uk/"
  weight = 50

[[main]]
  name = "About"
  pageRef = "/about/"
  weight = 60

[[social]]
  name = "X / Twitter"
  pre = "fab fa-x-twitter"
  url = "https://twitter.com/cedanews"
  weight = 10

[[social]]
  name = "YouTube"
  pre = "fab fa-youtube"
  url = "https://www.youtube.com/channel/UCYjSH2ET9nLMhDcXa5y2OMg"
  weight = 20

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/cedadev"
  weight = 30

#[[social]]
#  name = "LinkedIn"
#  pre = "fab linkedin"
#  url = "https://linkedin.com/"
#  weight = 40

#[[social]]
#  name = "Medium"
#  pre = "fab medium"
#  url = "https://medium.com/"
#  weight = 50

# toml-docs-start sample-navigation
# toml-docs-end sample-navigation